### ISSUE TITLE
Storeman Installer does not work at the GUI, but at the command line

### ISSUE THREAD

**Issue by Olf0** [storeman-developers/harbour-storeman-installer#1]
Storeman Installer did not work as intended on an XperiaX@SFOS3.2.1

I did:
1. `pkcon remove harbour-storeman`
2. `curl -LO https://openrepos.net/sites/default/files/packages/6416/harbour-storeman-installer-1.1.0-1.4.1.jolla_.noarch.rpm`
3. `pkcon install-local harbour-storeman-installer-1.1.0-1.4.1.jolla_.noarch.rpm`
4. Tap on the `Storeman Installer` desktop icon: It starts, is busy for a while and closes itself.

While step 4 ran as expected, the icon is still the `Storeman Installer` icon!
Hitting it again simply re-does step 4!
A `pkcon search name harbour-storeman` only shows
`Installed       harbour-storeman-installer-1.1.0-1.4.1.jolla.noarch (installed) Storeman Installer for Sailfish OS`
`Available       harbour-storeman-turing-0.0.26-1.armv7hl (openrepos-osetr)      OpenRepos Client for Turing Phone`
But `ssu lr` outputs
`Enabled repositories (global): `
` - mentaljam-obs   ... http://repo.merproject.org/obs/home:/mentaljam/3.2.1.20_armv7hl/`

Thinking "WTF!" and "this must be a very simple shell script", I looked 
at https://github.com/mentaljam/harbour-storeman-installer/blob/main/bin/harbour-storeman-installer
and https://github.com/mentaljam/harbour-storeman-installer/blob/main/harbour-storeman-installer.desktop
to be 100% sure to do the right thing and consequently executed `harbour-storeman-installer` at the CLI: Voilá, `Storeman` is installed!
Now a `pkcon search name harbour-storeman` shows
```                                                                                                                         
Installed       harbour-storeman-0.2.10+sfos3.2.20210906183000.9.ge94910a-1.9.1.jolla.armv7hl (installed)       OpenRepos Client for Sailfish OS
Available       harbour-storeman-debuginfo-0.2.10+sfos3.2.20210906183000.9.ge94910a-1.9.1.jolla.armv7hl (mentaljam-obs) Debug information for package harbour-storeman
Available       harbour-storeman-debugsource-0.2.10+sfos3.2.20210906183000.9.ge94910a-1.9.1.jolla.armv7hl (mentaljam-obs)       Debug sources for package harbour-storeman
Available       harbour-storeman-installer-1.1.0-1.4.1.jolla.noarch (openrepos-osetr)   Storeman Installer for Sailfish OS
Available       harbour-storeman-turing-0.0.26-1.armv7hl (openrepos-osetr)      OpenRepos Client for Turing Phone
```

I do not understand what was going on, do you?

But I think this would have been unresolvable for a pure GUI-user.

**Comment by mentaljam** [comment]
>I do not understand what was going on, do you?

The shell script is run under a normal user. I use polkit to allow the user to perform PackageKit actions. Maybe this approach is not applicable on SFOS3.2.1.

Can you try to install the installer and try to run the script as a normal user?

**Comment by Olf0** [comment]
> > I do not understand what was going on, do you?
> 
> The shell script is run under a normal user. I use polkit to allow the user to perform PackageKit actions.

I have seen that.  IMO you did that correctly.

> Maybe this approach is not applicable on SFOS3.2.1.

I am not aware of any change here, except that Jolla loves to alter group names and assignments (without a recognisable or documented reason).

BTW, the group `users` is not the right group IMO, because it contains *all* users, including guest users.  I assume your intention was to allow the primary user (i.e., `nemo` or `defaultuser`) to run this, correct?
For the very purpose here (using packagekit), I think the group `ssu` is the best fit.  A more generic, still suitable group would be `system`, but this was altered to `sailfish-system` by SFOS 3.4.0 or 4.0.1, so using that would need a `Identity=unix-group:system;unix-group:sailfish-system`.

> Can you try to install the installer and try to run the script as a normal user?

I think I did, when it succeded.  I just did not start it at the GUI.

**Comment by Olf0** [comment]
What I do faintly remember, is that I once had issues when globbing the actions.  IIRC this is the reason, why I stubbornly enumerated all actions here: https://github.com/Olf0/crypto-sdcard/blob/master/polkit-1/localauthority/50-local.d/69-cryptosd.pkla

I forgot how to enlist all possible actions, here for packagekit.  Can you please give me a hint, and I will try something.

**Comment by mar1ad** [comment]
Before upgrading to 4.3.0.15 I removed storeman, but after the upgrade I'm running into the same issue!?
Could it be due to polkit changes with this upgrade?

**Comment by Olf0** [comment]
> Before upgrading to 4.3.0.15 I removed storeman, but after the upgrade I'm running into the same issue!? Could it be due to polkit changes with this upgrade?

No, it is not the "same issue" and it has nothing to do with `polkit`.

Storeman Installer currently does not access Storeman for 4.3.0.15 at Sailfish-OBS.
The next release (v1.2.0) of Storeman Installer will resolve that.
Until then, please manually download and install Storeman, see https://github.com/storeman-developers/harbour-storeman/issues/160#issuecomment-1059112503

**Comment by Olf0** [comment]
See also (likely a duplicate of this issue) https://github.com/storeman-developers/harbour-storeman/issues/159

**Comment by mar1ad** [comment]
Thanks, storeman installer v1.2.0 works.

**Comment by Olf0** [comment]
So v1.2.0 worked on SFOS 4.3.0

v1.2.7 was confirmed to [work on a Jolla1@SFOS3.4.0](https://openrepos.net/comment/40596#comment-40596).

**Comment by Olf0** [comment]
Because Storeman Installer v2 does not use a desktop icon any longer, this issue has become moot.
